# https://github.com/yeasy/docker-compose-files/tree/master/hyperledger
# This compose file will start a Hyperledger Fabric 1.0 MVE, including
# * 2 ca (not in use now)
# * 1 orderer
# * 4 peers in 2 orgs

# * cli for testing

version: '2.0'

services:
  ca.org1.flowchain.io:
    extends:
      file: docker-compose-base-e2e.yaml
      service: ca.org1.flowchain.io

  ca.org2.flowchain.io:
    extends:
      file: docker-compose-base-e2e.yaml
      service: ca.org2.flowchain.io

  cli:
    extends:
      file: docker-compose-base-e2e.yaml
      service: cli

  orderer.flowchain.io:  # There  can be multiple orderers
    extends:
      file: docker-compose-base-e2e.yaml
      service: orderer.flowchain.io

  peer0.org1.flowchain.io:
    extends:
      file: docker-compose-base-e2e.yaml
      service: peer0.org1.flowchain.io

  peer1.org1.flowchain.io:
    extends:
      file: docker-compose-base-e2e.yaml
      service: peer1.org1.flowchain.io

  peer0.org2.flowchain.io:
    extends:
      file: docker-compose-base-e2e.yaml
      service: peer0.org2.flowchain.io

  peer1.org2.flowchain.io:
    extends:
      file: docker-compose-base-e2e.yaml
      service: peer1.org2.flowchain.io

#networks:
#  default:
#    external:
#      name: hyperledger_fabric
